export const BasicSentences = {
    A: "An apple is red.",
    B: "Birds fly in the sky.",
    C: "Cats like to play.",
    D: "Dogs are friendly pets.",
    E: "Elephants are big.",
    F: "Fish swim in water.",
    G: "Goats eat grass.",
    H: "Happy kids play games.",
    I: "Ice cream is sweet.",
    J: "Jump with joy.",
    K: "Kites fly high.",
    L: "Lions are brave.",
    M: "Monkeys like bananas.",
    N: "Nice friends share toys.",
    O: "Orange is my favorite fruit.",
    P: "Pandas eat bamboo.",
    Q: "Quiet time is reading time.",
    R: "Rabbits hop fast.",
    S: "Stars shine at night.",
    T: "Trees give us shade.",
    U: "Umbrellas keep us dry.",
    V: "Vegetables make us strong.",
    W: "Water helps plants grow.",
    X: "X marks the spot.",
    Y: "Yellow sun is bright.",
    Z: "Zebras have stripes."
};
  