export const AlphabetWords = {
    A: ['Apple', 'Ant', 'Airplane', 'Arrow', 'Astronaut'],
    B: ['Ball', 'Bear', 'Banana', 'Book', 'Butterfly'],
    C: ['Cat', 'Coding', 'Cake', 'Candy', 'Computer'],
    D: ['Dog', 'Door', 'Duck', 'Dolphin', 'Dragon'],
    E: ['Elephant', 'Eagle', 'Egg', 'Eye', 'Earth'],
    F: ['Fish', 'Flower', 'Friend', 'Flag', 'Fire'],
    G: ['Giraffe', 'Goat', 'Grass', 'Glass', 'Garden'],
    H: ['Horse', 'House', 'Hat', 'Heart', 'Hand'],
    I: ['Ice', 'Island', 'Igloo', 'Ink', 'Iron'],
    J: ['Jam', 'Juice', 'Jellyfish', 'Jacket', 'Jungle'],
    K: ['King', 'Kite', 'Kangaroo', 'Key', 'Kitchen'],
    L: ['Lion', 'Lamp', 'Leaf', 'Lemon', 'Ladder'],
    M: ['Moon', 'Mum', 'Mouse', 'Mango', 'Mountain'],
    N: ['Nest', 'Net', 'Night', 'Nurse', 'Nose'],
    O: ['Orange', 'Owl', 'Ocean', 'Octopus', 'Office'],
    P: ['Pig', 'Pencil', 'Panda', 'Pizza', 'Parrot'],
    Q: ['Queen', 'Quilt', 'Quarter', 'Question', 'Quiet'],
    R: ['Robot', 'Rabbit', 'Rainbow', 'Rose', 'Rocket'],
    S: ['Sun', 'Star', 'Snake', 'Spider', 'Ship'],
    T: ['Tree', 'Train', 'Tiger', 'Turtle', 'Table'],
    U: ['Umbrella', 'Unicorn', 'Up', 'Under', 'Uncle'],
    V: ['Van', 'Violin', 'Volcano', 'Voice', 'Vegetables'],
    W: ['Water', 'Window', 'Wolf', 'Watch', 'Whale'],
    X: ['Xylophone', 'X-ray', 'Fox', 'Box', 'Six'],
    Y: ['Yellow', 'Yoyo', 'Yacht', 'Yak', 'Yogurt'],
    Z: ['Zebra', 'Zoo', 'Zipper', 'Zero', 'Zigzag']
};